driver=chrome
mode=headed
fullname=mohanad mohamed
email=mohanadmohamed202100@gmail.com
emailAdmin=admin@test.com
password=012556680
passwordAdmin=admin123
phone=01287693236
city=alexandria
address=Egypt
bio=My name is mohanad mohamed iam trying to be QA Engineer as Embedded system has no jobs anymore
sql_username=mohanad
sql_password=mohanad
sql_url=jdbc:mysql://127.0.0.1:3306/qa_practice_platform